### ISSUE TITLE
Use the .f90 suffix

### ISSUE THREAD

**Issue by Beliavsky** [sarvex/fortran125#1]
I suggest using the .f90 suffix for your Fortran codes, not .fortran. The .f90 suffix means that the source code is free format, not that
the code conforms to the Fortran 90 standard. Code that uses the .f90 suffix can use features from any Fortran standard.  Most Fortran source code on GitHub that uses features from a standard more recent than Fortran 90 still uses the .f90 suffix.

**Comment by sarvex** [comment]
@Beliavsky  Thanks for the tip, I am new to Fortran, changed the extensions to .f90
